# Generated by Django 3.1.6 on 2021-02-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_name', models.CharField(max_length=50)),
                ('usr_crt', models.CharField(max_length=50)),
                ('dtm_crt', models.DateField(auto_now_add=True)),
                ('usr_upd', models.CharField(max_length=50)),
                ('dtm_upd', models.DateField(auto_now=True)),
            ],
        ),
    ]
