# Generated by Django 3.1.6 on 2021-02-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0002_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dukcapil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('maidenName', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('maritalStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marital.marital')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marital.religion')),
            ],
        ),
    ]
